Question_Bank= [
  {"test": "Google's original search engine prototype was called 'BackRub'.", "answer": True},
  {"test": "The state of Meghalaya is home to 'living root bridges' that are grown, not built, by the local Khasi people.", "answer": True},
  {"test": "The popular game 'Snakes and Ladders' originated in India as a moral board game called 'Moksha Patam'.", "answer": True},
  {"test": "Bluetooth technology was named after a 10th-century Danish king famous for his dead, dark blue tooth.", "answer": True},
  {"test": "The concept of 'Shampoo' originated in ancient Greece.", "answer": False},
  {"test": "Nintendo originally started as a company that sold handmade playing cards in 1889.", "answer": True},
  {"test": "Maharashtra's Lonar Lake was created by a meteor impact over 50,000 years ago.", "answer": True},
  {"test": "The modern game of Polo originated in the Indian state of Manipur.", "answer": True},
  {"test": "The USB (Universal Serial Bus) standard was co-invented by an Indian-American computer architect named Ajay Bhatt.", "answer": True},
  {"test": "There is a village in Maharashtra called Shani Shingnapur where houses have no front doors.", "answer": True},
  {"test": "The first Apple logo featured Isaac Newton sitting under an apple tree.", "answer": True},
  {"test": "Chess was invented in India during the Gupta Empire and was originally known as 'Chaturanga'.", "answer": True},
  {"test": "India's first floating post office is located on Lake Pichola in Rajasthan.", "answer": False},
  {"test": "The Pentium chip's development was led by an Indian-American engineer named Vinod Dham, known as the 'Father of the Pentium chip'.", "answer": True},
  {"test": "Samsung initially started as a grocery trading store in 1938.", "answer": True},
  {"test": "The village of Kongthong in Meghalaya is known as the 'Whistling Village' because residents call each other using unique musical tunes instead of names.", "answer": True},
  {"test": "Hotmail was co-founded by an Indian entrepreneur named Sabeer Bhatia.", "answer": True},
  {"test": "Sikkim was the first state in the world to become 100% organic in its agriculture.", "answer": True},
  {"test": "Olympic gold medals are made entirely of solid gold.", "answer": False},
  {"test": "The martial art form 'Kalaripayattu', considered one of the oldest surviving in the world, originated in Kerala.", "answer": True},
  {"test": "Amazon was originally going to be called 'Cadabra' (as in abracadabra).", "answer": True},
  {"test": "The state of Gujarat has the only sanctuary in the world for the Asiatic wild ass.", "answer": True},
  {"test": "The 'Fi' in WiFi officially stands for 'Frequency Internet'.", "answer": False},
  {"test": "Golf is the only sport to have been played on the surface of the moon.", "answer": True},
  {"test": "Mawsynram in Meghalaya holds the Guinness World Record for the highest average annual rainfall.", "answer": True},
  {"test": "In the early 1900s, Tug-of-War was an official Olympic sport.", "answer": True},
  {"test": "The programming language 'Java' was originally named 'Oak' after a tree outside the creator's office.", "answer": True},
  {"test": "The highest cricket ground in the world is located in Chail, Himachal Pradesh.", "answer": True},
  {"test": "Fiber optics were pioneered by an Indian-born physicist named Narinder Singh Kapany.", "answer": True},
  {"test": "Majuli in Assam is currently recognized as the largest river island in the world.", "answer": True},
  {"test": "McDonald's originally opened as a restaurant that exclusively sold hot dogs, not hamburgers.", "answer": True},
  {"test": "Viswanathan Anand was the first sports personality in India to win the prestigious Padma Vibhushan.", "answer": True},
  {"test": "The Bandra Worli Sea Link in Mumbai contains enough steel wire to wrap around the circumference of the earth.", "answer": True},
  {"test": "The word 'robot' comes from a Czech word meaning 'forced labor'.", "answer": True},
  {"test": "Kerala is home to the Padmanabhaswamy Temple, widely considered the wealthiest place of worship in the world.", "answer": True},
  {"test": "The sport of Snooker was invented by British Army officers stationed in India in the late 19th century.", "answer": True},
  {"test": "Twitter's original iconic blue bird mascot was officially named 'Larry' after basketball legend Larry Bird.", "answer": True},
  {"test": "The Magnetic Hill in Ladakh creates a gravity-defying optical illusion where vehicles appear to roll uphill.", "answer": True},
  {"test": "Sachin Tendulkar once fielded for the Pakistan cricket team as a substitute during a practice match in 1987.", "answer": True},
  {"test": "India's first rocket was transported to the Thumba launch pad on a bullock cart.", "answer": False},
  {"test": "The world's largest stone sundial is located in the Jantar Mantar observatory in Jaipur, Rajasthan.", "answer": True},
  {"test": "The shortest officially recorded professional boxing match in history lasted just 4 seconds.", "answer": True},
  {"test": "CAPTCHA stands for 'Completely Automated Public Turing test to tell Computers and Humans Apart'.", "answer": True},
  {"test": "Basketball was originally invented using peach baskets as the hoops.", "answer": True},
  {"test": "Khari Baoli in New Delhi operates as the largest wholesale spice market in Asia.", "answer": True},
  {"test": "The first international cricket match in history was played between the USA and Canada in 1844.", "answer": True},
  {"test": "The current Indian Rupee symbol (₹) was designed by an IIT postgraduate named Udaya Kumar and adopted in 2010.", "answer": True},
  {"test": "India has a sanctuary dedicated entirely to protecting the Sloth Bear, located in Karnataka.", "answer": True},
  {"test": "Table Tennis was originally marketed under the name 'Wiff Waff'.", "answer": True},
  {"test": "The state of Goa was a Portuguese territory for over 450 years before being annexed by India in 1961.", "answer": True},
  {"test": "Diamond mining and extraction in the world first originated in India.", "answer": True},
  {"test": "The 'Tour de France' originally started as a publicity stunt to increase the sales of a French sports newspaper.", "answer": True},
  {"test": "Varanasi is believed to be one of the oldest continuously inhabited cities in the entire world.", "answer": True},
  {"test": "The Eiffel Tower can grow up to 15 cm taller during the summer due to the thermal expansion of iron.", "answer": True},
  {"test": "Oxford University was founded later than the Aztec Empire in Mexico.", "answer": False},
  {"test": "India won its first-ever Olympic gold in field hockey in 1928 without conceding a single goal in the entire tournament.", "answer": True},
  {"test": "Saudi Arabia routinely imports sand and camels from Australia.", "answer": True},
  {"test": "The concept of 'Zero' as a full-fledged number was first developed in ancient India.", "answer": True},
  {"test": "A single day on the planet Venus is longer than a whole year on Venus.", "answer": True},
  {"test": "Tomatoes, potatoes, and green chilies are native to India and have been grown there for thousands of years.", "answer": False},
  {"test": "Rabindranath Tagore is the only person to have authored the national anthems of two different countries (India and Bangladesh).", "answer": True},
  {"test": "The Apple iPhone's clock in almost all official advertisements is set to 9:41 AM, the exact time Steve Jobs unveiled the first iPhone.", "answer": True},
  {"test": "Bhutan is the only country in the world that is officially carbon negative, absorbing more CO2 than it produces.", "answer": True},
  {"test": "The presence of 'Water on the Moon' was first definitively discovered by India's Chandrayaan-1 mission.", "answer": True},
  {"test": "The Great Wall of China is easily visible from space with the naked eye.", "answer": False},
  {"test": "Peanuts are not actually nuts; they are scientifically classified as legumes.", "answer": True},
  {"test": "The game of Badminton was initially known as 'Poona' because it was popularized by British officers stationed in Pune.", "answer": True},
  {"test": "The national animal of Scotland is the Unicorn.", "answer": True},
  {"test": "There are currently more plastic fake flamingos in the world than living ones.", "answer": True},
  {"test": "Vande Bharat Express trains are manufactured without any external engine cars, utilizing distributed traction power.", "answer": True},
  {"test": "Cleopatra lived closer in time to the invention of the iPhone than she did to the building of the Great Pyramid of Giza.", "answer": True},
  {"test": "Wombat poop is completely cube-shaped to stop it from rolling away off rocks.", "answer": True},
  {"test": "The famous 'Windows XP bliss' default wallpaper is a real, unedited photograph taken in California.", "answer": True},
  {"test": "A 'jiffy' is an actual scientific unit of time measuring 1/100th of a second.", "answer": True},
  {"test": "The chainsaw was originally invented by doctors to assist in difficult childbirth procedures.", "answer": True},
  {"test": "Freddie Mercury, the iconic lead singer of Queen, was of Indian Parsi descent and spent much of his childhood studying in India.", "answer": True},
  {"test": "The highest grossing Indian film globally, 'Dangal', actually earned more money at the Chinese box office than it did in India.", "answer": True},
  {"test": "High heels were originally designed for Persian male soldiers to secure their feet in stirrups while riding horses.", "answer": True},
  {"test": "The tiny extra pocket on a pair of jeans was originally designed by Levi Strauss to store pocket watches.", "answer": True},
  {"test": "Blood donors in Sweden receive an automated text message whenever their donated blood is used to save a patient.", "answer": True},
  {"test": "Bananas naturally grow curved because they defy gravity and reach for the sunlight, a process called negative geotropism.", "answer": True},
  {"test": "Sloths can hold their breath underwater for up to 40 minutes, which is longer than dolphins can.", "answer": True},
  {"test": "Honey is the only natural food that never spoils; archaeologists have found 3,000-year-old honey in Egyptian tombs that is perfectly edible.", "answer": True},
  {"test": "The tiny dot over the lowercase letters 'i' and 'j' has a specific name; it is called a 'tittle'.", "answer": True},
  {"test": "Water actually makes a different pouring sound depending on whether it is hot or cold.", "answer": True},
  {"test": "Woolly mammoths were still roaming the Earth 1,000 years after the Egyptians finished building the Great Pyramid of Giza.", "answer": True},
  {"test": "An adult human body has exactly the same number of bones as a newborn baby.", "answer": False},
  {"test": "Oscar-winning British actor Sir Ben Kingsley's birth name is Krishna Pandit Bhanji.", "answer": True},
  {"test": "The letter 'J' was the very last letter to be added to the English alphabet.", "answer": True},
  {"test": "India currently produces and exports more than 70% of the entire world's spices.", "answer": True},
  {"test": "The first computer mouse ever invented was made out of wood.", "answer": True},
  {"test": "A standard baseball used in Major League Baseball has exactly 108 red stitches.", "answer": True},
  {"test": "Serena Williams won the 2017 Australian Open Grand Slam tournament while she was roughly two months pregnant.", "answer": True},
  {"test": "The first printed book in world history was printed in India.", "answer": False},
  {"test": "The Indian state of Arunachal Pradesh is known as the 'Land of the Rising Sun' because it receives the first sunrise in India.", "answer": True},
  {"test": "Michael Phelps has won more Olympic gold medals individually than the entire country of Mexico has won in its history.", "answer": True},
  {"test": "The longest officially recorded professional tennis match took over 11 hours to complete.", "answer": True},
  {"test": "Nokia was originally founded in 1865 as a single paper mill operation.", "answer": True},
  {"test": "India holds the world record for planting the most trees in a single day, with volunteers in Uttar Pradesh planting over 50 million in 24 hours.", "answer": True},
  {"test": "The game of Ludo is derived from the ancient Indian game of Pachisi.", "answer": True}
]